--liquibase formatted sql

--changeset batuhan:1
--comment: Initial chess schema for users and games
--preconditions onFail:MARK_RAN

-- 1. USERS TABLE
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users'
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       external_id UUID NOT NULL UNIQUE,
                       username VARCHAR(100) NOT NULL UNIQUE,
                       email VARCHAR(150) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       elo_rating INTEGER NOT NULL DEFAULT 1200,
                       total_wins INTEGER NOT NULL DEFAULT 0,
                       total_losses INTEGER NOT NULL DEFAULT 0,
                       total_draws INTEGER NOT NULL DEFAULT 0,
                       role VARCHAR(50) NOT NULL,
                       is_guest BOOLEAN NOT NULL DEFAULT FALSE,
                       created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. GAMES TABLE
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'games'
CREATE TABLE games (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       white_player_id BIGINT,
                       black_player_id BIGINT,
                       pgn_data TEXT,
                       result VARCHAR(50),
                       finish_method VARCHAR(50),
                       white_elo_before INTEGER NOT NULL,
                       black_elo_before INTEGER NOT NULL,
                       white_elo_gain INTEGER,
                       black_elo_gain INTEGER,
                       played_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_game_white_player FOREIGN KEY (white_player_id) REFERENCES users(id),
                       CONSTRAINT fk_game_black_player FOREIGN KEY (black_player_id) REFERENCES users(id)
);
