--liquibase formatted sql

--changeset batuhan:3
--comment: Create audit_logs table for tracking administrative actions

CREATE TABLE audit_logs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            admin_id BIGINT NOT NULL,
                            action_type VARCHAR(100) NOT NULL,
                            details TEXT,
                            created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT fk_audit_log_admin FOREIGN KEY (admin_id) REFERENCES users(id)
);
